name: App
on: [push]
jobs:
  test:
    steps:
      - name: Install go
        uses: actions/setup-go@v2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: make test
